version: '3.2'

services:
  mysql:
    image: mysql:5.7.30
    hostname: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123454321
      MYSQL_USER: caoyawen
      MYSQL_PASSWORD: jkddcba32
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ${DOCKER_COMPOSE_VOL}/mrm/mysql5_7_30:/var/lib/mysql

  redis:
    image: redis:6
    hostname: redis
    ports:
      - "16379:6379"
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis:/usr/local/etc/redis/
      - ${DOCKER_COMPOSE_VOL}/mrm/redis:/data

  mongo:
    image: mongo:4
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: caoyawen
      MONGO_INITDB_ROOT_PASSWORD: dkanci83
    ports:
      - "37017:27017"
#    volumes:
#      - ${DOCKER_COMPOSE_VOL}/mrm/mongo:/data/db

  redis-insight:
    image: redislabs/redisinsight
    ports:
      - "18101:8001"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "18102:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: caoyawen
      PMA_PASSWORD: jkddcba32

  mongo-express:
    image: mongo-express
    ports:
      - "18103:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: caoyawen
      ME_CONFIG_BASICAUTH_PASSWORD: dkanci83
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: caoywen
      ME_CONFIG_MONGODB_ADMINPASSWORD: dkanci83
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

